version: "3.7"
services:
  proyectos-microservicio: #micro servicio
    container_name: "proyectos-microservicio"
    image: proyectos-microservicio:v1
    build:
      context: ./api-rest-node-micro-servicio #la imagen busca el docker file del micro servicio
    ports:
      - "4000:4000"
    networks:
      - proyectos
    depends_on:
      - proyectos-database
    restart: always

  proyectos-core: #monolito
    container_name: "proyectos-core"
    image: proyectos-core:v1
    build:
      context: ./api-rest-node-monolito #la imagen busca el docker file del monolito
    ports:
      - "4001:9000"
    networks:
      - proyectos
    depends_on:
      - proyectos-database
    restart: always

  proyectos-database: #base de datos
    container_name: "proyectos-database"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - proyectos
    volumes:
      - mongo-database:/data/db

volumes:
  mongo-database:
networks:
  proyectos:
